name = "{{project-name}}"
main = "build/worker/shim.mjs"
compatibility_date = "{{ "now" | date: "%Y-%m-%d" }}"
account_id = "{{account_id}}"

assets = { directory = "./src/ui/build/" }

[build]
command = "cargo install -q worker-build && worker-build --release"

# Watch only the main Rust entrypoint to avoid trigerring many reloads when the
# UI is built.
watch_dir = "src/lib.rs"

[dev]
port = 8123
